# 라이브러리 선언

In [2]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

#회귀 모델 ANN 실습

## 회귀 데이터 불러오기

In [3]:
from sklearn.datasets import load_boston
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [5]:
x = boston.data
y = boston.target

In [7]:
x.shape, y.shape

((506, 13), (506,))

## 데이터 분리

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(x,y,test_size=0.3)

In [9]:
print(x_train.shape, y_train.shape)

(354, 13) (354,)


## 모델링 Sequential API

In [12]:
#모델 선언
model_sqn_rgs = keras.models.Sequential()

#레이어 추가
model_sqn_rgs.add(keras.layers.Input((13,)))
model_sqn_rgs.add(keras.layers.Dense(32,'relu'))
model_sqn_rgs.add(keras.layers.Dense(32,'relu'))
model_sqn_rgs.add(keras.layers.Dense(1))

#모델 컴파일
model_sqn_rgs.compile(loss='mse',optimizer='adam')

#모델 학습
model_sqn_rgs.fit(x_train,y_train,epochs=10,verbose=1)



Epoch 1/10
12/12 [==============================] - 0s 2ms/step - loss: 11973.9658
Epoch 2/10
12/12 [==============================] - 0s 2ms/step - loss: 620.4163
Epoch 3/10
12/12 [==============================] - 0s 2ms/step - loss: 521.4877
Epoch 4/10
12/12 [==============================] - 0s 2ms/step - loss: 186.8882
Epoch 5/10
12/12 [==============================] - 0s 2ms/step - loss: 111.6475
Epoch 6/10
12/12 [==============================] - 0s 2ms/step - loss: 93.0578
Epoch 7/10
12/12 [==============================] - 0s 2ms/step - loss: 80.4945
Epoch 8/10
12/12 [==============================] - 0s 2ms/step - loss: 73.8810
Epoch 9/10
12/12 [==============================] - 0s 2ms/step - loss: 69.6796
Epoch 10/10
12/12 [==============================] - 0s 1ms/step - loss: 66.2271


In [14]:
print(y_val[:10])
print(model_sqn_rgs.predict(x_val).reshape(-1)[:10])

[22.4 30.3 20.6 16.1 12.  20.2 16.8 22.  11.7 18.9]
[22.91025   26.298347  22.8818     8.839511  14.825522  24.869944
 26.069471  29.336393   7.1893716 23.681059 ]


## 모델링 Functional API

In [15]:
print(x_train.shape, y_train.shape)

(354, 13) (354,)


In [18]:
#레이어 선언
il = keras.layers.Input(13)
h1 = keras.layers.Dense(32)(il)
h2 = keras.layers.Dense(32)(h1)
ol = keras.layers.Dense(1)(h2)

#모델 선언
model_fcn_rgs = keras.models.Model(il,ol)

#모델 컴파일
model_fcn_rgs.compile(loss='mse',optimizer='adam')

#모델 학습
model_fcn_rgs.fit(x_train,y_train,epochs=10,verbose=1)


Epoch 1/10
12/12 [==============================] - 0s 2ms/step - loss: 9997.2861
Epoch 2/10
12/12 [==============================] - 0s 1ms/step - loss: 2458.5505
Epoch 3/10
12/12 [==============================] - 0s 1ms/step - loss: 808.3491
Epoch 4/10
12/12 [==============================] - 0s 1ms/step - loss: 329.9885
Epoch 5/10
12/12 [==============================] - 0s 2ms/step - loss: 165.6569
Epoch 6/10
12/12 [==============================] - 0s 1ms/step - loss: 126.3856
Epoch 7/10
12/12 [==============================] - 0s 2ms/step - loss: 108.0193
Epoch 8/10
12/12 [==============================] - 0s 1ms/step - loss: 108.2394
Epoch 9/10
12/12 [==============================] - 0s 2ms/step - loss: 115.4660
Epoch 10/10
12/12 [==============================] - 0s 1ms/step - loss: 99.6526


In [19]:
print(y_val[:10])
print(model_fcn_rgs.predict(x_val).reshape(-1)[:10])

[22.4 30.3 20.6 16.1 12.  20.2 16.8 22.  11.7 18.9]
[20.815323  22.669506  19.612282   4.5357857 19.691452  24.092922
 20.897045  26.424305   3.1900365 19.754509 ]


# 분류모델 ANN 실습

## 분류 데이터 불러오기

In [20]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [21]:
x = cancer.data
y = cancer.target

x.shape, y.shape

((569, 30), (569,))

## 데이터 분리

In [22]:
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(x,y,test_size=.2,random_state=2022)

In [23]:
print(x_train.shape, y_train.shape)

(455, 30) (455,)


## 모델링 Sequential API

In [25]:
#모델 선언
model_seq_cls = keras.models.Sequential()

#레이어 추가
model_seq_cls.add(keras.layers.Input(30))
model_seq_cls.add(keras.layers.Dense(32,'sigmoid'))
model_seq_cls.add(keras.layers.Dense(32,'sigmoid'))
model_seq_cls.add(keras.layers.Dense(1,'sigmoid'))

#모델 컴파일
model_seq_cls.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

#모델 학습
model_seq_cls.fit(x_train,y_train,epochs=10,verbose=1)

Epoch 1/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6962 - accuracy: 0.5231
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6371 - accuracy: 0.6352
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6223 - accuracy: 0.6352
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6110 - accuracy: 0.6352
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5969 - accuracy: 0.6352
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5865 - accuracy: 0.6352
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5727 - accuracy: 0.6352
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5598 - accuracy: 0.6352
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5447 - accuracy: 0.6352
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5333 - accuracy: 0.6374


In [29]:
print(y_val[:10])
pred = model_seq_cls.predict(x_val).reshape(-1)
pred_res = np.where(pred>0.7,1,0)
print(pred_res[:10])

[1 1 0 1 1 1 1 0 0 0]
[1 1 1 1 1 1 0 0 0 0]


## 모델링 Functional API

In [31]:
#레이어 선언
il = keras.layers.Input(30)
h1 = keras.layers.Dense(32,'sigmoid')(il)
h2 = keras.layers.Dense(32,'sigmoid')(h1)
ol = keras.layers.Dense(1,'sigmoid')(h2)

#모델 선언
model_fnc_cls = keras.models.Model(il,ol)

#모델 컴파일
model_fnc_cls.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

#모델 학습
model_fnc_cls.fit(x_train,y_train,epochs=10,verbose=1)




Epoch 1/10
15/15 [==============================] - 0s 1ms/step - loss: 0.8722 - accuracy: 0.3648
Epoch 2/10
15/15 [==============================] - 0s 1ms/step - loss: 0.7150 - accuracy: 0.4945
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6502 - accuracy: 0.6352
Epoch 4/10
15/15 [==============================] - 0s 1ms/step - loss: 0.6371 - accuracy: 0.6352
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6291 - accuracy: 0.6352
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6228 - accuracy: 0.6352
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6158 - accuracy: 0.6352
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6091 - accuracy: 0.6352
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6005 - accuracy: 0.6352
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5930 - accuracy: 0.6352


In [32]:
print(y_val[:10])
pred = model_seq_cls.predict(x_val).reshape(-1)
pred_res = np.where(pred>0.7,1,0)
print(pred_res[:10])

[1 1 0 1 1 1 1 0 0 0]
[1 1 1 1 1 1 0 0 0 0]
