# Keras Sequential API

## Linear Regression


### 라이브러리 호출

In [2]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

### 데이터 생성

In [3]:
y_lst = [x*2 + 1 for x in range(0,11)]

x = np.array(range(0,11))
y = np.array(y_lst)

In [5]:
print(x)
print(y)

print('shape of x : ',x.shape)
print('shape of y : ',y.shape)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19 21]
shape of x :  (11,)
shape of y :  (11,)


### 모델링

In [6]:
# 케라스 세션 클리어
keras.backend.clear_session()

#모델 선언
model = keras.models.Sequential()

#레이어 추가
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1))

#모델 컴파일
model.compile(loss = 'mse' , optimizer='adam')

#모델 학습
model.fit(x,y,epochs=10,verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 579ms/step - loss: 79.5317
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 79.4108
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 79.2899
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 79.1692
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 79.0486
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 78.9281
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 78.8077
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 78.6874
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 78.5672
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 78.4471


In [7]:
print(model.predict(x).reshape(-1))
print(y)

[0.0099975  0.65813625 1.306275   1.9544138  2.6025527  3.2506914
 3.8988302  4.5469685  5.1951075  5.8432465  6.491385  ]
[ 1  3  5  7  9 11 13 15 17 19 21]


----
## Boston 데이터로 모델 학습

### 데이터 불러오기

In [9]:
from sklearn.datasets import load_boston
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [11]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

### 모델링

In [13]:
# 케라스 세션 클리어
keras.backend.clear_session()

#모델 선언
model_boston = keras.models.Sequential()

#레이어 추가
model_boston.add(keras.layers.Input(shape=(13,)))
model_boston.add(keras.layers.Dense(1))

#모델 컴파일
model_boston.compile(loss='mse', optimizer='adam')

#모델 학습
model_boston.fit(x,y,epochs=10,verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 113669.7812
Epoch 2/10
16/16 [==============================] - 0s 3ms/step - loss: 104079.8672
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 94915.0781
Epoch 4/10
16/16 [==============================] - 0s 3ms/step - loss: 86467.3594
Epoch 5/10
16/16 [==============================] - 0s 3ms/step - loss: 78589.7656
Epoch 6/10
16/16 [==============================] - 0s 3ms/step - loss: 71233.3125
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 64417.5977
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 58200.3047
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 52346.3711
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 47087.8203


In [15]:
print(model_boston.predict(x).reshape(-1)[:5])
print(y[:5])

[-143.90042 -128.74472 -123.72013 -115.80247 -117.86544]
[24.  21.6 34.7 33.4 36.2]


-----
-----
## Logistic Regression : 유방암 데이터

In [16]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [18]:
x = cancer.data
y = cancer.target

x.shape, y.shape

((569, 30), (569,))

In [22]:
# 케라스 세션 클리어
keras.backend.clear_session()

#모델 선언
model_cancer = keras.models.Sequential()

#레이어 추가
model_cancer.add(keras.layers.Input(shape=(30,)))
model_cancer.add(keras.layers.Dense(1,activation='sigmoid'))

#모델 컴파일
model_cancer.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

#모델 학습
model_cancer.fit(x,y,epochs=10,verbose=1)

Epoch 1/10
18/18 [==============================] - 1s 3ms/step - loss: 1.0425 - accuracy: 0.8946
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 0.6040 - accuracy: 0.8875
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 0.5635 - accuracy: 0.9227
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 0.5468 - accuracy: 0.9086
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 0.5239 - accuracy: 0.9192
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 0.5229 - accuracy: 0.9139
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 0.5224 - accuracy: 0.9156
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 0.5178 - accuracy: 0.9086
Epoch 9/10
18/18 [==============================] - 0s 2ms/step - loss: 0.5075 - accuracy: 0.9209
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 0.5072 - accuracy: 0.9104


In [24]:
print(model_cancer.predict(x).reshape(-1)[:10])
print(y[:10])

[0.0000000e+00 4.7399735e-35 1.6038484e-27 1.4171174e-01 1.9208638e-11
 2.0547948e-07 5.4881117e-28 8.3965273e-13 1.2773573e-03 4.2186571e-06]
[0 0 0 0 0 0 0 0 0 0]
