# Keras Functional API

## Linear Regression

### 라이브러리 호출

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

### 데이터 생성

In [2]:
x = np.array(range(0,11))
y = np.array([x*2 + 1 for x in range(0,11)])

print(x,x.shape)
print(y,y.shape)

[ 0  1  2  3  4  5  6  7  8  9 10] (11,)
[ 1  3  5  7  9 11 13 15 17 19 21] (11,)


### 모델링

In [3]:
# 케라스 세션 클리어
keras.backend.clear_session()

#레이어 선언
il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

#모델 선언
model = keras.models.Model(il,ol)

#모델 컴파일
model.compile(loss='mse',optimizer='adam')

#모델 학습
model.fit(x,y,epochs=10,verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 533ms/step - loss: 221.1030
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 220.9016
Epoch 3/10
1/1 [==============================] - 0s 10ms/step - loss: 220.7002
Epoch 4/10
1/1 [==============================] - 0s 13ms/step - loss: 220.4989
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 220.2977
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 220.0966
Epoch 7/10
1/1 [==============================] - 0s 9ms/step - loss: 219.8957
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 219.6948
Epoch 9/10
1/1 [==============================] - 0s 18ms/step - loss: 219.4940
Epoch 10/10
1/1 [==============================] - 0s 14ms/step - loss: 219.2933


In [4]:
print(model.predict(x).reshape(-1))
print(y)

[ 0.00999848 -0.34893125 -0.70786095 -1.0667907  -1.4257205  -1.7846502
 -2.1435797  -2.5025096  -2.8614392  -3.2203689  -3.5792987 ]
[ 1  3  5  7  9 11 13 15 17 19 21]


----
## Boston 데이터로 Linear Regression 모델 학습

### 데이터 불러오기

In [5]:
from sklearn.datasets import load_boston
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [6]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

### 모델링

In [8]:
#케라스 세션 클리어
keras.backend.clear_session()

#레이어 선언
il_boston = keras.layers.Input(shape=(13,))
ol_boston = keras.layers.Dense(1)(il_boston)

#모델 선언
model_boston = keras.models.Model(il_boston,ol_boston)

#모델 컴파일
model_boston.compile(loss='mse',optimizer='adam')

#모델 학습
model_boston.fit(x,y,epochs=10,verbose=1)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 38143.6719
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 33327.1055
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 29013.1953
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 25268.9609
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 22026.0723
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 19261.0371
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 16991.5781
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 15005.0000
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 13368.8682
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 12053.7637


In [9]:
print(model_boston.predict(x).reshape(-1)[:5])
print(y[:5])

[ 14.287211 -24.159346 -10.927733 -17.082907 -23.225101]
[24.  21.6 34.7 33.4 36.2]


----
-----
## Logistic Regression : 유방암 데이터

In [10]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [11]:
x = cancer.data
y = cancer.target

x.shape, y.shape

((569, 30), (569,))

In [12]:
#케라스 세션 클리어
keras.backend.clear_session()

#레이어 선언
il = keras.layers.Input(shape=(30,))
ol = keras.layers.Dense(1,activation='sigmoid')(il)

#모델 선언
model_cancer = keras.models.Model(il,ol)

#모델 컴파일
model_cancer.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

#모델 학습
model_cancer.fit(x,y,epochs=10,verbose=1)

Epoch 1/10
18/18 [==============================] - 1s 2ms/step - loss: 118.6973 - accuracy: 0.3726
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 104.5359 - accuracy: 0.3726
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 89.9473 - accuracy: 0.3726
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 75.7830 - accuracy: 0.3726
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 61.5454 - accuracy: 0.3726
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 47.1583 - accuracy: 0.3726
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 32.7489 - accuracy: 0.3761
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 19.4938 - accuracy: 0.3831
Epoch 9/10
18/18 [==============================] - 0s 2ms/step - loss: 10.5298 - accuracy: 0.3937
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 9.1087 - accuracy: 0.4552


In [13]:
print(model_cancer.predict(x).reshape(-1)[:10])
print(y[:10])

[1.0000000e+00 2.3821109e-05 7.4442250e-01 1.0000000e+00 1.7870895e-17
 1.0000000e+00 9.9190521e-01 1.0000000e+00 9.9998975e-01 1.0000000e+00]
[0 0 0 0 0 0 0 0 0 0]
